POST http://country_currency_api.test/api/countries/refresh
###
GET http://country_currency_api.test/api/countries

###
GET http://country_currency_api.test/api/countries?region=Africa
Accept: application/json

###
GET http://country_currency_api.test/api/countries?currency=NGN
Accept: application/json

###
GET http://country_currency_api.test/api/countries?sort=gdp_desc
Accept: application/json

###
GET http://country_currency_api.test/api/countries?region=Africa&currency=NGN&sort=gdp_desc
Accept: application/json

###
GET http://country_currency_api.test/api/countries?name=Nigeria
Accept: application/json

###
GET http://country_currency_api.test/api/countries/Nigeria

###
DELETE http://country_currency_api.test/api/countries/Nigeria

###
GET http://country_currency_api.test/api/status


###
GET http://country_currency_api.test/api/countries/refresh

###
POST http://country_currency_api.test/api/countries
Content-Type: application/json

{
    "name": "Nigeria"
}

###
GET http://country_currency_api.test/api/countries

###
GET http://country_currency_api.test/api/countries/image


###
POST http://country_currency_api.test/api/countries/refresh

###
GET http://country_currency_api.test/api/countries/image

###
GET https://country-currency-main-vzxm73.laravel.cloud/api/countries?region=Africa&sort=gdp_desc

###
GET http://country_currency_api.test/api/countries/Nigeria

###
GET http://country_currency_api.test/api/invalidroute
